# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ULISES
email: hello@ulises.us
description: >
    Ulises / Books / Curation
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hello-ulises

# Build settings
markdown: kramdown
highlighter: rouge
incremental: false

gems:
    - jekyll-feed
    - jemoji

exclude:
    - Gemfile
    - Gemfile.lock
    - vendor
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - gulpfile.js
    - node_modules
    - README.md
    - components

encoding: "utf-8"
markdown_ext: "md"

kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: expanded

prose:
  rooturl: '_posts'
  media: 'assets/img'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "select"
          label: "column"
          placeholder: "choose column"
          options:
            - name: "left"
              value: "left"
            - name: "right"
              value: "right"
      - name: "tags"
        field:
          element: "multiselect"
          label: "tags"
          placeholder: "choose or add tags"
          alterable: true
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME